# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
default_velocity_scaling_factor: 10.0
default_acceleration_scaling_factor: 5.0

joint_limits:
  ur5_elbow_joint:
    has_velocity_limits: true
    max_velocity: 5.15
    has_acceleration_limits: true
    max_acceleration: 3.5
  ur5_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 5.15
    has_acceleration_limits: true
    max_acceleration: 3.5
  ur5_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 5.15
    has_acceleration_limits: true
    max_acceleration: 3.5
  ur5_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: true
    max_acceleration: 3.5
  ur5_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: true
    max_acceleration: 3.5
  ur5_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: true
    max_acceleration: 3.5
